server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/company/**
          filters:
            - RewritePath=/account/(?<path>.*), /$\{path}
        - id: customer-service
          uri: lb://control-service
          predicates:
            - Path=/control/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}


eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


