server:
  servlet:
    context-path: /control
  port: 8081

spring:
  r2dbc:
    username: postgres
    password: 123
    url: r2dbc:postgresql://localhost:5432/test_control_service

  data:
    r2dbc:
      repositories:
        enabled: true

  liquibase:
    user: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/test_control_service
    change-log: classpath:liquibase/db.changelog-master.xml

